# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

mod.mc_dep=[VERSIONED]
mod.mc_title=[VERSIONED]
mod.mc_targets=[VERSIONED]
deps.parchment=[VERSIONED]
deps.fabric_api=[VERSIONED]

deps.fabric_loader=0.18.4
deps.kotlin_fabric_loader=1.13.8+kotlin.2.3.0

mod.version=1.0.0
mod.group=io.github.seggan
mod.name=Choir Flowers
mod.id=choir-flowers
